project:
  type: website
  output-dir: docs

website:
  title: "RVA"
  description: "Renato Vargas | Economist | Data Scientist"
  navbar:
    left:
      - href: blog
        text: Blog
      - href: about.qmd#sec-publications
        text: Publications
      - href: about.qmd
        text: About
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/revargas/
      - icon: rss
        href: index.xml
    pinned: true
  cookie-consent: true
  google-analytics:
    tracking-id: "G-60B40THQ4Y"
    anonymize-ip: false
    type: express
    style: simple
  site-url: "https://renatovargas.com"
resources:
  - CNAME

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    mainfont: monospace



