project:
  type: website
  output-dir: docs

website:
  title: "RVA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - href: about.qmd#sec-publications
        text: Publications
      - href: about.qmd
        text: About
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/revargas/
      - icon: whatsapp
        href:  https://wa.me/50251556635
  cookie-consent: true
  google-analytics:
    tracking-id: "G-60B40THQ4Y"
    anonymize-ip: true
  site-url: "https://renatovargas.com"
resources:
  - CNAME

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



